all:
  hosts:
    ubuntu01:
      internal_ip: 10.0.2.10
    ubuntu02:
      internal_ip: 10.0.2.11
    ubuntu03:
      internal_ip: 10.0.2.12
  children:
    ubuntuhosts:
      vars:
        ssh_port: 2222
        ssh_key_bits: 4096
        internal_subnet: 24
      hosts:
        ubuntu01:
        ubuntu02:
        ubuntu03:
