all:
  hosts:
    ubuntu01:
      internal_ip: 10.0.2.10
    ubuntu02:
      internal_ip: 10.0.2.11
    ubuntu03:
      internal_ip: 10.0.2.12
    ubuntu04:
      internal_ip: 10.0.2.13
    ubuntu05:
      internal_ip: 10.0.2.14
    ubuntu06:
      internal_ip: 10.0.2.15
    ubuntu07:
      internal_ip: 10.0.2.16
    ubuntu08:
      internal_ip: 10.0.2.17
    ubuntu09:
      internal_ip: 10.0.2.18
  children:
    ubuntuhosts:
      vars:
        ssh_port: 2222
        ssh_key_bits: 4096
        internal_subnet: 24
      hosts:
        ubuntu01:
        ubuntu02:
        ubuntu03:
        ubuntu04:
        ubuntu05:
        ubuntu06:
        ubuntu07:
        ubuntu08:
        ubuntu09: